### ISSUE TITLE
周回数の管理はクランと分離する

### ISSUE THREAD

**Issue by drakontia** [yuina1056/ClanBattleBot#20]
今DBにおいてクランの中に周回数が埋め込まれていますが、毎度リセットする手間が発生するので、イベントごとにした方がいいと思います。

**Comment by yuina1056** [comment]
eventは他クランでも利用するマスタになるので、周回数を保持するテーブル追加する方向性が良さそう。

**Comment by drakontia** [comment]
イベントごとって、イベントのところに埋め込むんじゃなくて、イベントごとの周回数をもつテーブルを作成するっていうそういう意味でした。
