### ISSUE TITLE
Reportに持ち越しかの判定だけでなく、持ち越しが発生したかの判定が必要

### ISSUE THREAD

**Issue by drakontia** [yuina1056/ClanBattleBot#26]
今、持ち越しかの判定でisCarryOverがあると思いますが、その凸で持ち越しが発生したかの判定も必要だと思われます。
あとで集計する際に削りか撃破だけだと持ち越しが発生しているかの区別をするのが困難です。
なので、hasCarryOverという発生判定を付ける必要があると思います。

**Comment by yuina1056** [comment]
#72 で対応済み
