### ISSUE TITLE
githubActionで色々チェックしたい

### ISSUE THREAD

**Issue by yuina1056** [yuina1056/ClanBattleBot#38]
- トランスコンパイル通るかチェック
- pritterとかeslintチェックしたい
  - PRで解決済み！感謝ァ！

**Comment by drakontia** [comment]
dprintよさげ
https://kakehashi-dev.hatenablog.com/entry/2023/11/27/103000

**Comment by yuina1056** [comment]
prettierよりも並行モードでも早いんか・・・
prettierから移行するかどうか検討するissue作って検討する方向にする。
