### ISSUE TITLE
持ち越しが発生しているかの判定が機能していない

### ISSUE THREAD

**Issue by drakontia** [yuina1056/ClanBattleBot#55]
以下のところで判定していますが、機能していません。
https://github.com/yuina1056/ClanBattleBot/blob/622ebab9348e58e35e88715ac8405c25adf776d7/src/commands/button/report_defeat.ts#L160-L171

おそらく、取得したreportsのlengthを厳密に0か判定していますが、nullかなんかが返ってきているのを想定できていません。
なので、毎度判定がすり抜けます。
findの返り値を確認して、的確に判定する必要があります。

**Comment by yuina1056** [comment]
#54 で修正済み
