### ISSUE TITLE
解凍処理を実装する

### ISSUE THREAD

**Issue by drakontia** [yuina1056/ClanBattleBot#93]
解凍とは、凸宣言をしている状態で救援などで凸宣言の対象であるボスが撃破された際に凸宣言をキャンセルさせるものである。
解凍操作自体は、凸宣言のキャンセルで実施出来るが、~~よりわかりやすくするために別途解凍ボタンを設置した方がいいと思われる~~操作のし忘れなどの防止に実装しておいた方がいい。
処理としては、解凍対象のボスに凸宣言されているものを一律で消去すれば問題ないと考えられる。

**Comment by yuina1056** [comment]
解凍ボタンの設置よりは撃破時に宣言が残っている場合は凸取り消しと同じ動きをするほうがわかりやすそう

**Comment by drakontia** [comment]
![image](https://github.com/yuina1056/ClanBattleBot/assets/639777/6d7392b8-a198-4888-898d-a2331dd5f671)

**Comment by yuina1056** [comment]
#97 で対応完了したのでクローズ
